---
title: "Geography 385 Spatial Data Analysis"
subtitle: "Spring 2025"
html:
    theme: cosmo 
pdf:
    colorlinks: true
---

<hr>


## Class Meetings

| Meeting | Location | Time                    |
|---------|----------|-------------------------|
| Lecture | GMCS 307  | Tue & Thu 2:00 - 3:15pm |

## Instructor

| Name                                                     | Office hours                                                                  | Location                                                                                                                      |
|----------------------------------------------------------|-------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------|
| [Sergio Rey](https://geography.sdsu.edu/people/bios/rey) | [Mon 3:00 - 4:00pm (by appointment)](https://calendly.com/sjsrey/office-hours) | [PSFA 361G](https://map.concept3d.com/?id=801#!ce/12160?ct/62917,40419,40418,20161,15205,48503,54894,16202,12164?m/147097?s/) |



## Introduction

Welcome to GEOG 385: Spatial Data Analysis!

The purpose of this course is to introduce you to methods of spatial
data analysis. The focus is on both the conceptual and applied aspects
of spatial statistical methods. We will place particular emphasis on
the computational aspects of Exploratory Spatial Data Analysis (ESDA)
methods for diﬀerent types of spatial data with a particular focus on
point processes and lattice (areal unit) data. Throughout the course
you will gain valuable hands-on experience with several specialized
software packages for spatial data analysis. The overriding goal of
the course is for you to acquire familiarity with the fundamental
methodological and operational issues in the statistical analysis of
geographic information and the ability to extend these methods in your
own research.

The course takes an explicitly computational thinking approach to its
pedagogy. Students are introduced to computational concepts and tools that are
increasingly important to research that engages with geospatial data. By
adopting these tools, students acquire a deeper engagement with, and mastery of,
the substantive concepts. Put differently, students will *learn to code*. But
this is a means to the end goal: students will *code to learn* spatial data
analysis.


In the scope of a 15-week semester course we can only introduce a handful
of the key concepts and methods relevant to the field of spatial data analysis. As
such, the course is not intended as an exhaustive treatment. Instead,
the goal is that students will acquire an understanding of the more
common and useful methods and practices, and use the course as an entry
point for further engagement with the field.

## Prerequisites


- [GEOG 101](https://catalog.sdsu.edu/preview_course_nopop.php?catoid=5&coid=31440) or [GEOG 102](https://catalog.sdsu.edu/preview_course_nopop.php?catoid=5&coid=31442) 
- [STAT 250](https://catalog.sdsu.edu/preview_course_nopop.php?catoid=5&coid=33000) or comparable course in statistics.

All students are required to complete the [prerequisite assessment quiz](https://sdsu.instructure.com/courses/157862/quizzes/324219) before 2025-01-23 2:00pm.

## Computational Learning

We will be using [open
source](https://en.wikipedia.org/wiki/Open-source_software) geospatial
software throughout the course together with [Jupyter
Notebooks](https://jupyter.org), and [Python](https://python.org) as our
scripting language.

All software for the course will be made available through
[JupyterHub](https://jupyter.org/), a web-based framework. Students
wishing to install these materials on their own machines will be given
instructions to do so, **but this is not required**.

## Readings

All required readings are available through the links listed
below. Assigned readings should be completed before the date listed in
the schedule (see below). Readings are a critical part of the
discussions we will hold in class, and therefore being prepared for class
means having completed the readings and thought about the
content. It will be difficult to do well in this course without having
completed the readings.

| Abbrevation | Source                                                                                        |
|-------------|-----------------------------------------------------------------------------------------------|
| [RAW][gds]  | Rey, S.J., D. Arribas-Bel, L.J. Wolf (2023) Geographic Data Science with Python. CRC Press.   |
| [THW][gda]  | Tenkanen, H., V. Heikinheimo, D. Whipp (2023) Python for Geographic Data Analysis. CRC Press. |



## Schedule (Planned)

|         Week | Date  | Topic                              | Readings                | Exercise  |         Quiz |
|-------------:|:------|:-----------------------------------|:------------------------|-----------|-------------:|
|            1 | 01-21 | Introduction                       |                         |           |              |
|              | 01-23 | Computational Resources            | [RAW 2][gds2], [JL][jl] |           | Prerequisite |
|            2 | 01-28 | Exploratory Spatial Data  Analysis | [RAW 1][gds1]           | One out   |            1 |
|              | 01-30 | Spatial Data Models                | [RAW 3][gds3]           |           |              |
|            3 | 02-04 | Coordinate Reference Systems       | [THW 5.3][gda53]        |           |            2 |
|              | 02-06 | Distances                          | [CA21][smdistance]      |           |              |
|            4 | 02-11 | [PySAL Geoprocessing][pg]          | [RAW 4][gds4]           |           |            3 |
|              | 02-13 | [PySAL Spatial Graphs][ps]         | [RAW 4][gds4]           |           |            4 |
|            5 | 02-18 | Visualization                      | [VIZ][VIZ]              | One due   |            5 |
|              | 02-20 | Geovisualization                   | [BOKGV][bokgv]          | Two out   |              |
|            6 | 02-25 | Classification Schemes             | [RAW 5][gds5]           |           |            6 |
|              | 02-27 | Choropleth Mapping                 | [RAW 5][gds5]           |           |              |
|            7 | 03-04 | Point Pattern Visualization        | [DABVPP][dabvpp]        |           |            7 |
|              | 03-06 | Kernel Density Estimation          | [DABVPP][dabvpp]        |           |            8 |
|            8 | 03-11 | Review                             |                         | Two due   |              |
|              | 03-13 | *Exam 1*                           |                         |           |              |
|            9 | 03-18 | Global Autocorrelation             | [RAW 6][gds6]           | Three out |            9 |
|              | 03-20 | Global Autocorrelation Tests       | [RAW 6][gds6]           |           |              |
|           10 | 03-25 | Local Autocorrelation              | [RAW 7][gds7]           |           |           10 |
|              | 03-27 | Local Autocorrelation Tests        | [RAW 7][gds7]           |           |              |
| Spring Break | 03-31 |                                    |                         |           |              |
|           11 | 04-08 | Nearest Neighbor Relations         | [RAW 8][gds8]           |           |           11 |
|              | 04-10 | Nearest Neighbor Tests             | [RAW 8][gds8]           |           |              |
|           12 | 04-15 | Nearest Neighbor Distances         | [RAW 8][gds8]           | Three due |           12 |
|              | 04-17 | Distance Based Tests               | [RAW 8][gds8]           | Four out  |              |
|           13 | 04-22 | Clustering Point Patterns          | [DABPC][dabpc]          |           |           13 |
|              | 04-24 | Regionalization                    | [RAW 10][gds10]         |           |              |
|           14 | 04-29 | Interpolation Point Based          | [DS6.6][ds66]           | 13        |           14 |
|              | 05-01 | Kriging                            | [DS6.7][ds67]           |           |              |
|           15 | 05-06 | Interpolation Area Based           | [DS4.2][ds42]           |           |           15 |
|              | 05-08 | Review                             |                         | Four due  |              |
|              | 05-13 | *Exam 2 (1pm)*                     |                         |           |              |




[jl]: https://jupyterlab.readthedocs.io/en/stable/user/interface.html
[gds1]: https://geographicdata.science/book/intro.html
[gds2]: https://geographicdata.science/book/notebooks/02_geospatial_computational_environment.html#
[gds3]: https://geographicdata.science/book/notebooks/03_spatial_data.html
[gda53]: https://pythongis.org/part2/chapter-05/nb/02-introduction-to-coordinate-reference-systems.html#
[smdistance]: https://storymaps.arcgis.com/stories/ad3f3984f4d54a5982429d29421d1627
[gds4]: https://geographicdata.science/book/notebooks/04_spatial_weights.html
[VIZ]: https://guides.library.jhu.edu/datavisualization/home#s-lg-box-25364137
[bokgv]: https://gistbok-topics.ucgis.org/CV-05-035
[pg]: https://sdsu.instructure.com/courses/166767/pages/pysal-geoprocessing
[ps]:  https://sdsu.instructure.com/courses/166767/pages/pysal-weights
[gds5]: https://geographicdata.science/book/notebooks/05_choropleth.html
[dabvpp]: https://www.youtube.com/watch?v=niRHJxb4PQM&ab_channel=DanielArribas-Bel
[gds6]: https://geographicdata.science/book/notebooks/06_spatial_autocorrelation.html
[gds7]: https://geographicdata.science/book/notebooks/07_local_autocorrelation.html
[gds8]: https://geographicdata.science/book/notebooks/08_point_pattern_analysis.html
[gds10]: https://geographicdata.science/book/notebooks/10_clustering_and_regionalization.html
[ds66]: https://www.spatialanalysisonline.com/HTML/index.html?deterministic_interpolation_me.htm
[ds67]: https://www.spatialanalysisonline.com/HTML/index.html?geostatistical_interpolation_m.htm
[ds42]: https://www.spatialanalysisonline.com/HTML/index.html?areal_interpolation.htm
[tob]: https://pysal.org/tobler/tutorial.html
[dabpc]: https://www.youtube.com/watch?v=u5sz1PVeJMo&list=PLaYT7Y2aK2d6vs3h38jnjrTEpSS7VYLwU&index=20&ab_channel=DanielArribas-Bel


			  				  
[pp]: studio/python_course.qmd
[quiz]: https://sdsu.instructure.com/courses/157862/quizzes/324219

[draft]: https://sdsu.instructure.com/courses/157862/assignments/1445749
[s12]: https://sdsu.instructure.com/courses/157862/assignments/1445786

[gda]: https://pythongis.org/index.html
[gda3]: https://pythongis.org/part1/chapter-03/index.html
[gda6]: https://pythongis.org/part2/chapter-06/index.html#
[gds]: https://geographicdata.science/book/intro.html 
[gds1]: https://geographicdata.science/book/notebooks/01_geo_thinking.html
[gds2]: https://geographicdata.science/book/notebooks/02_geospatial_computational_environment.html
[gds3]: https://geographicdata.science/book/notebooks/03_spatial_data.html
[gds8.1]: https://geographicdata.science/book/notebooks/08_point_pattern_analysis.html
[gds8.2]: https://geographicdata.science/book/notebooks/08_point_pattern_analysis.html#centrography
[gds8.3]: https://geographicdata.science/book/notebooks/08_point_pattern_analysis.html#randomness-clustering
[gds9]: https://geographicdata.science/book/notebooks/09_spatial_inequality.html
[gds11]: https://geographicdata.science/book/notebooks/11_regression.html 
[gdsii]: https://geographicdata.science/book/intro_part_ii.html
[gds5]:  https://geographicdata.science/book/notebooks/05_choropleth.html
[gds6.1]:  https://geographicdata.science/book/notebooks/06_spatial_autocorrelation.html#understanding-spatial-autocorrelation
[gds4]: https://geographicdata.science/book/notebooks/04_spatial_weights.html
[gds5.1]:  https://geographicdata.science/book/notebooks/06_spatial_autocorrelation.html#binary-case-join-counts
[gds5.2]: https://geographicdata.science/book/notebooks/06_spatial_autocorrelation.html#continuous-case-moran-plot-and-moran-s-i
[gds6]: https://geographicdata.science/book/notebooks/07_local_autocorrelation.html
[gdsreg]: https://geographicdata.science/book/notebooks/10_clustering_and_regionalization.html
[gsags]: https://www.spatialanalysisonline.com/HTML/geostatistical_interpolation_m.htm?zoom_highlightsub=geostatistical
[gsakrg]: https://www.spatialanalysisonline.com/HTML/kriging_interpolation.htm 
[gsaint]: https://www.spatialanalysisonline.com/HTML/deterministic_interpolation_me.htm
[gsanet]: https://www.spatialanalysisonline.com/HTML/network_and_location_analysis.htm
[gsareg]: https://www.spatialanalysisonline.com/HTML/regression_overview.htm?zoom_highlightsub=regression
[sahmv]: https://www.statsref.com/HTML/multivariate_distributions.html?zoom_highlightsub=multivariate
[sahcor]: https://www.statsref.com/HTML/correlation.html
[sahinf]: https://www.statsref.com/HTML/simple_regression.html
[python]: http://python.org
[ds6]: https://www.spatialanalysisonline.com/HTML/surface_and_field_analysis.htm
[ds65]: https://www.spatialanalysisonline.com/HTML/deterministic_interpolation_me.htm
[ds67]: https://www.spatialanalysisonline.com/HTML/geostatistical_interpolation_m.htm


## Grading



GEOG 385 uses [specification
grading](https://www.insidehighered.com/views/2016/01/19/new-ways-grade-more-effectively-essay)
in evaluating student work and in determining your final course grade.
The quality and quantity of your work will determine your course grade.
The acceptable level of quality demonstrates competency in the
concepts and methods covered in the course.

There is a two-step process for determination of your final course grade
at the end of the quarter:

1.  Using your scores on quizzes and  exercises, your **base grade** is
    determined.
2.  Using your  exam results, determine if your base grade includes
    a \"plus\", \"minus\", or level drop to form the course grade.


### Base Grade
For Step 1, the base grade is determined using the following
specification:

Thresholds for base grade:

| Item\\Base      | A  | B  | C | D |
|-----------|---:|---:|--:|--:|
| **Quizzes**   | 12 | 10 | 8 | 6 |
| **Exercises** | 4  | 3  | 2 | 1 |

You must pass the both thresholds to obtain the base grade.

### Final Grade
For Step 2, your final course grade is determined as follows:

- Exam average 90 or above, "+" added to base grade
- Exam average 75-89, no adjustment
- Exam average 60-74, "-" added to base grade
- Exam average <60, one grade below base grade

Examples of Final Grade Determination:

| Exam\\Base | A  | B  | C  | D  |
|-----------|----|----|----|----|
| **90+**       | A  | B+ | C+ | D+ |
| **75-89**     | A  | B  | C  | D  |
| **60-74**     | A- | B- | C- | D- |
| **<60**       | B  | C  | D  | F  |


::: {.callout-note}
Note that SDSU grading policy does not allow A+ grades.
However, if you have a base grade of A and score 90+ on your exam average, you are eligible for a letter of recommendation from the professor.
:::

 

## Quizzes

Starting in week two there will be a quiz due before a session that pertains to
the background reading that is required before our work in class.  Quizzes are
graded on a pass/fail basis.

## Exercises

Four exercises are assigned on the dates listed in the syllabus. These
 exercises are evaluated based on whether they demonstrate a
 sufficient understanding of the covered content. When an assignment
 is deemed satisfactory, it indicates that the student has effectively
 showcased their comprehension of the subject matter.



## Tokens {#sec-tokens}

Each student is provided with three tokens at the beginning of the
semester.

### Using Tokens


1. Credit for a reading quiz that was failed (1 token).

1. Obtaining a one-day extension for an exercise  prior to due date (1 token).

2. Revising  an exercise  that was submitted on-time but evaluated as unsatisfactory (2 tokens).

3. Requesting a make-up date for an exam  (3 tokens scheduled at least 2 weeks before exam date)


## Policies
### Accommodations
If you are a student with a disability and are in need of
accommodations for this class, please contact Student Ability
Success Center at (619) 594-6473 as soon as possible.  Please know
accommodations are not retroactive, and I cannot provide
accommodations based upon disability until I have received an
accommodation letter from Student Ability Success Center.

### Privacy and Intellectual Property
Student Privacy and Intellectual Property: The Family Educational
Rights and Privacy Act (FERPA) mandates the protection of student
information, including contact information, grades, and graded
assignments. I will use Canvas to communicate with you,
and I will not post grades or leave graded assignments in public
places. Students will be notified at the time of an assignment if
copies of student work will be retained beyond the end of the semester
or used as examples for future students or the wider public. Students
maintain intellectual property rights to work products they create as
part of this course unless they are formally notified otherwise.


### Academic Integrity

The SDSU student academic integrity policy lists violations in detail.
These violations fall into eight broad areas that include but are not
limited to: cheating, fabrication, plagiarism, facilitating academic
misconduct, unauthorized collaboration, interference or sabotage,
non-compliance with research regulations and retaliation. For more
information about the SDSU student academic integrity policy, please see
the following: <https://sacd.sdsu.edu/student-rights/academic-dishonesty>.


### Code of Conduct

As course instructor, I am dedicated to providing a harassment-free
learning experience for all students, regardless of gender, sexual
orientation, disability, physical appearance, body size, race, religion,
or choice of operating system. All course participants are expected to
show respect and courtesy to other students throughout the semester. As
a learning community we do not tolerate harassment of participants in
any form.

-   All communication should be appropriate for a professional audience
    including people of many different backgrounds. Sexual language and
    imagery are not appropriate in this course.

-   Be kind to others. Do not insult or put down other students. Behave
    professionally. Remember that harassment and sexist, racist, or
    exclusionary jokes are not appropriate for this course.

-   Students violating these rules may be asked to leave the course, and
    their violations will be reported to the SDSU administration.

This code of conduct is an adaptation of the [SciPy 2018 Code of
Conduct](https://scipy2018.scipy.org/ehome/299527/648147/index9a04.html).

